namespace Agronomia.Domain.Interfaces;

/// <summary>
/// Defines the contract for invoking the configured GenAI model.
/// </summary>
public interface IAzureAIAgentService
{
    /// <summary>
    /// Sends a prompt to the configured agent/model and returns the generated response.
    /// </summary>
    /// <param name="prompt">User input or question.</param>
    /// <param name="outputFormat">Optional desired json output schema.</param>
    /// param name="image">Optional image stream to provide additional context.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Model response text with metadata.</returns>
    Task<AgentResponse> RunAsync(string prompt, string? outputFormat = null, MemoryStream? image = null, CancellationToken cancellationToken = default);
}

/// <summary>
/// Represents a response generated by the GenAI agent.
/// </summary>
/// <param name="Answer">Text returned by the model.</param>
/// <param name="AgentName">Friendly agent name.</param>
/// <param name="ModelId">Underlying deployment or model identifier.</param>
public sealed record AgentResponse(string Answer, string AgentName, string ModelId);
