/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#50da0b",
        "primary-dark": "#42b609",
        "primary-hover": "#44b909",
        "background-light": "#f6f8f5",
        "background-dark": "#162210",
        "surface-light": "#ffffff",
        "surface-dark": "#1c2b18",
        "surface-light-muted": "#f9fcf8",
        "surface-dark-muted": "#25361f",
        "surface-dark-soft": "#253818",
        "text-main": "#131811",
        "text-main-light": "#121c0d",
        "text-main-dark": "#f0fdf4",
        "text-muted": "#6e8a60",
        "text-muted-light": "#a0c490",
        "text-placeholder": "#a3bba2",
        "text-secondary-light": "#659c49",
        "text-secondary-dark": "#a3d984",
        "text-on-primary": "#0d1609",
        "border-color": "#dfe6db",
        "border-light": "#ebf4e7",
        "border-dark": "#2a3c22",
        "border-strong": "#3a4d33",
        "border-muted": "#d7e8ce",
        "border-subtle": "#eef3ec",
        "accent-lime": "#ecfccb",
        "accent-olive": "#4d7c0f",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontSize: {
        "display-xl": ["2.5rem", { lineHeight: "1.1" }],
        "display-lg": ["2.25rem", { lineHeight: "1.1" }],
        "display-md": ["2rem", { lineHeight: "1.15" }],
        "heading-lg": ["1.5rem", { lineHeight: "1.25" }],
        "heading-md": ["1.25rem", { lineHeight: "1.3" }],
        "body-lg": ["1rem", { lineHeight: "1.6" }],
        "body-md": ["0.95rem", { lineHeight: "1.6" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5" }],
        caption: ["0.75rem", { lineHeight: "1.4" }],
      },
      boxShadow: {
        card: "0 8px 30px rgb(0 0 0 / 0.04)",
        "card-dark": "0 8px 30px rgb(0 0 0 / 0.2)",
      },
    },
  },
  plugins: [],
};
